services:
  api:
    build:
      context: ..
      dockerfile: ./compose/Dockerfile
    image: pes_apiv1_ci
    environment:
      PES_APIV1_ENVIRONMENT: pytest
      PES_APIV1_SENTRY_DSN: ""
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: pes_apiv1
      POSTGRES_PASSWORD: pes_apiv1
      POSTGRES_DB: pes_apiv1_test
      PES_APIV1_DB_ECHO: "False"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.3-bullseye
    hostname: db
    environment:
      POSTGRES_PASSWORD: pes_apiv1
      POSTGRES_USER: pes_apiv1
      POSTGRES_DB: pes_apiv1_test
    healthcheck:
      test: pg_isready -U pes_apiv1
      interval: 2s
      timeout: 3s
      retries: 40
